import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms and conditions for using the Kapsa study app.",
};

export default function TermsOfService() {
  return (
    <div className="pt-32 pb-24">
      <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
        <div className="mb-12">
          <h1 className="font-heading text-4xl font-bold text-white">Terms of Service</h1>
          <p className="mt-3 text-white/40">Last updated: February 19, 2026</p>
        </div>

        <div className="prose-custom space-y-8">
          <Section title="1. Acceptance of Terms">
            <p>
              By downloading, installing, or using Kapsa (&ldquo;the App&rdquo;), you agree to be bound by
              these Terms of Service (&ldquo;Terms&rdquo;). If you do not agree to these Terms, do not use
              the App. These Terms constitute a legal agreement between you and Bagasy Studio
              (&ldquo;we,&rdquo; &ldquo;our,&rdquo; or &ldquo;us&rdquo;).
            </p>
          </Section>

          <Section title="2. Description of Service">
            <p>
              Kapsa is an AI-powered study companion that helps students organize their study
              materials, generate flashcards and quizzes, and track their academic progress. The App
              provides the following services:
            </p>
            <ul>
              <li>AI-powered chat assistant (Oracle) for study guidance</li>
              <li>Document capture and text extraction using optical character recognition (OCR)</li>
              <li>Automated flashcard and quiz generation from study materials</li>
              <li>Course organization and study material management</li>
              <li>Study progress tracking, analytics, and streak monitoring</li>
              <li>Calendar-based study scheduling</li>
            </ul>
          </Section>

          <Section title="3. User Accounts">
            <p>
              To use Kapsa, you must create an account. You are responsible for maintaining the
              confidentiality of your account credentials and for all activities that occur under your
              account. You agree to:
            </p>
            <ul>
              <li>Provide accurate and complete information during registration</li>
              <li>Keep your account information up to date</li>
              <li>Notify us immediately of any unauthorized use of your account</li>
              <li>Not share your account with others or create multiple accounts</li>
            </ul>
          </Section>

          <Section title="4. Subscription Terms">
            <h4>4.1 Free Tier</h4>
            <p>
              Kapsa offers a free tier with limited features. Free users have access to basic
              functionality with usage limits on AI features.
            </p>

            <h4>4.2 Kapsa Pro</h4>
            <p>
              Kapsa Pro is a premium subscription that unlocks additional features including
              unlimited AI chat, test generation, smart study plans, and advanced analytics.
              Subscriptions are available on a monthly ($12.99/month) or yearly ($59.99/year) basis.
            </p>

            <h4>4.3 Billing and Renewal</h4>
            <ul>
              <li>Subscriptions are processed through Apple&apos;s App Store and are subject to Apple&apos;s terms and conditions.</li>
              <li>Subscriptions automatically renew unless cancelled at least 24 hours before the end of the current billing period.</li>
              <li>You can manage and cancel your subscription at any time through your Apple ID account settings.</li>
              <li>No refunds will be provided for partial subscription periods, except as required by applicable law.</li>
            </ul>

            <h4>4.4 Free Trial</h4>
            <p>
              We may offer a free trial period for Kapsa Pro. If you do not cancel before the trial
              ends, you will be automatically charged for the subscription plan you selected. Free
              trial eligibility is determined by Apple and may only be available once per Apple ID.
            </p>
          </Section>

          <Section title="5. User Content">
            <h4>5.1 Your Content</h4>
            <p>
              You retain ownership of all content you upload, create, or share through the App,
              including study materials, notes, photos, and audio recordings (&ldquo;User Content&rdquo;). By
              using the App, you grant us a limited, non-exclusive license to process your User
              Content solely for the purpose of providing the App&apos;s services to you.
            </p>

            <h4>5.2 AI-Generated Content</h4>
            <p>
              Content generated by our AI features (flashcards, quizzes, summaries, chat responses)
              is provided &ldquo;as is&rdquo; for educational purposes only. While we strive for accuracy, AI-
              generated content may contain errors or inaccuracies. You are responsible for verifying
              the accuracy of AI-generated content before relying on it for academic purposes.
            </p>

            <h4>5.3 Prohibited Content</h4>
            <p>You agree not to upload or share content that:</p>
            <ul>
              <li>Violates any applicable law or regulation</li>
              <li>Infringes on intellectual property rights of others</li>
              <li>Contains malicious code, viruses, or harmful material</li>
              <li>Is offensive, defamatory, or inappropriate</li>
              <li>Attempts to reverse engineer or exploit our AI systems</li>
            </ul>
          </Section>

          <Section title="6. Intellectual Property">
            <p>
              The App, its design, features, functionality, and all related intellectual property are
              owned by Bagasy Studio. You may not copy, modify, distribute, sell, or lease any part
              of the App without our prior written consent. The Kapsa name, logo, and branding are
              trademarks of Bagasy Studio.
            </p>
          </Section>

          <Section title="7. Acceptable Use">
            <p>You agree not to:</p>
            <ul>
              <li>Use the App for any unlawful purpose or in violation of these Terms</li>
              <li>Attempt to gain unauthorized access to the App or its systems</li>
              <li>Interfere with or disrupt the App&apos;s servers or networks</li>
              <li>Use automated tools to scrape, crawl, or extract data from the App</li>
              <li>Circumvent any usage limits or access restrictions</li>
              <li>Impersonate any person or entity</li>
              <li>Use the App for commercial purposes without authorization</li>
            </ul>
          </Section>

          <Section title="8. Disclaimer of Warranties">
            <p>
              The App is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of any kind, either
              express or implied, including but not limited to implied warranties of
              merchantability, fitness for a particular purpose, and non-infringement. We do not
              guarantee that the App will be uninterrupted, error-free, or completely secure.
            </p>
            <p>
              AI-generated content is for educational reference only and should not be considered a
              substitute for professional academic instruction. We make no guarantees regarding
              academic outcomes or grade improvements.
            </p>
          </Section>

          <Section title="9. Limitation of Liability">
            <p>
              To the maximum extent permitted by applicable law, Bagasy Studio shall not be liable
              for any indirect, incidental, special, consequential, or punitive damages, or any loss
              of profits or revenues, whether incurred directly or indirectly, or any loss of data,
              use, goodwill, or other intangible losses resulting from:
            </p>
            <ul>
              <li>Your use or inability to use the App</li>
              <li>Any unauthorized access to your account or data</li>
              <li>Errors, inaccuracies, or omissions in AI-generated content</li>
              <li>Any interruption or cessation of the App&apos;s services</li>
            </ul>
          </Section>

          <Section title="10. Termination">
            <p>
              We reserve the right to suspend or terminate your account at any time if you violate
              these Terms. Upon termination, your right to use the App will cease immediately. You
              may also delete your account at any time through the App settings. Termination does not
              affect any rights or obligations that accrued prior to the termination date.
            </p>
          </Section>

          <Section title="11. Changes to These Terms">
            <p>
              We may modify these Terms at any time. If we make material changes, we will notify you
              through the App or by other means. Your continued use of the App after changes take
              effect constitutes acceptance of the revised Terms.
            </p>
          </Section>

          <Section title="12. Governing Law">
            <p>
              These Terms shall be governed by and construed in accordance with applicable law,
              without regard to conflict of law provisions. Any disputes arising from these Terms or
              your use of the App shall be resolved through binding arbitration or in the courts of
              competent jurisdiction.
            </p>
          </Section>

          <Section title="13. Contact Us">
            <p>
              If you have any questions about these Terms, please contact us at:
            </p>
            <ul>
              <li><strong>Email:</strong> support@kapsa.app</li>
              <li><strong>Developer:</strong> Bagasy Studio</li>
            </ul>
          </Section>
        </div>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h3 className="font-heading text-xl font-semibold text-white mb-4">{title}</h3>
      <div className="space-y-3 text-white/50 text-[15px] leading-relaxed [&_h4]:text-white/70 [&_h4]:font-semibold [&_h4]:mt-4 [&_h4]:mb-2 [&_h4]:text-base [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-2 [&_strong]:text-white/60">
        {children}
      </div>
    </section>
  );
}
